---
# ls Lint configuration file
# This file is used to configure the ls-lint tool, which checks file names and paths in a project.
# It specifies the naming conventions for different file types and directories,
# as well as files and directories to ignore.
# For more information, see: https://ls-lint.org/

# Naming conventions:
# - snakecase: all lowercase letters, words separated by underscores (e.g., my_file.py)
# - kebabcase: all lowercase letters, words separated by hyphens (e.g., my-file.py)
ls:
  .py: snakecase
  .dir: snakecase
  .md: snakecase
  .yml: snakecase | kebabcase
  .yaml: snakecase | kebabcase
  .toml: snakecase
  .txt: snakecase
  .json: snakecase | kebabcase
  .sh: kebabcase

# Ignore list:
ignore:
  - .devcontainer
  - .git
  - .github
  - .github/ISSUE_TEMPLATE
  - megalinter-reports
  - .vscode
  - dist
  - build
  - .pytest_cache
  - __pycache__
  - README.md
