---
# MegaLinter GitHub Action configuration file
# More info at https://megalinter.io
name: Run Mega-MegaLinter

# This action only runs on "master" branch as it takes too much time.
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions: read-all

jobs:
  mega-mega-linter:
    name: Mega-MegaLinter
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push, comment issues & post new PR
      # Remove the ones you do not need
      contents: read
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit # Monitor outbound connections

      # Git Checkout
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # Mega-MegaLinter
      - name: Mega-MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/latest/flavors/
        uses: oxsecurity/megalinter@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7 # v9.5.0
        env:
          # https://megalinter.io/latest/configuration/
          # Disable linters in the listed descriptors
          # DISABLE: COPYPASTE
          # Disable specific linters
          DISABLE_LINTERS: SPELL_CSPELL,RST_RSTFMT,PYTHON_RUFF_FORMAT,PYTHON_ISORT,RST_RST_LINT,PYTHON_BANDIT,JSON_PRETTIER,PYTHON_PYRIGHT,PYTHON_PYLINT,PYTHON_FLAKE8,REPOSITORY_KICS,SPELL_LYCHEE,BASH_EXEC
          # Report results to GitHub status checks
          GITHUB_STATUS_REPORTER: true
          # Python default style to check/apply.
          PYTHON_DEFAULT_STYLE: ruff
          # Displays elapsed time in reports
          SHOW_ELAPSED_TIME: true
          # Validate all files in the codebase, not only modified files
          VALIDATE_ALL_CODEBASE: true
